### ISSUE TITLE
Using with realtime game server

### ISSUE THREAD

**Issue by Webkadabra** [jsuarez5341/neural-mmo#14]
If this is possible, I would appreciate it very very much if in couple of words, you could outline if it is possible to use this project with a different game API, provided this game has Python lib? 

I understand all skills and other game-specific things I will have to re-write, but was hoping I could re-use parts of NeuralMMO code, since I'm very new to both Python and OpenAI itself.

**Comment by jsuarez5341** [comment]
Sure -- It depends on which aspects of the project you'd like to use. The infrastructure is set up to handle envs with a large and variable number of agents. You could simplify it significantly if you wanted to use a game env without those requirements. Probably the experience collection and some of the policy code would be reusable directly, but your best bet is to just use this project as a reference point for setting up the various components of an RL training pipeline.

If you'd like to chat more, I check the NMMO Discord multiple times per day
