### ISSUE TITLE
websocket connection problem

### ISSUE THREAD

**Issue by zhaishengfu** [jsuarez5341/neural-mmo#18]
https://github.com/jsuarez5341/neural-mmo-client/issues/7

**Comment by zhaishengfu** [comment]
OK now I know the reason. This is because the autobahn version!! My is 20.0, and I delete this and install 19.3.3, this problem disappeared!!!

**Comment by jsuarez5341** [comment]
Glad you solved it -- quicker replies on Discord in the future. I updated the dependencies list to include the correct autobahn version a while ago. Maybe you were working off an older commit?
