### ISSUE TITLE
strange agent action

### ISSUE THREAD

**Issue by zhaishengfu** [jsuarez5341/neural-mmo#19]
![problem](https://user-images.githubusercontent.com/7630101/74792872-964a2f80-52f9-11ea-99f4-5136a2c9b4bb.png)

Hi, the agent always do the same stupid action of moving from one place to another and there is only one agent, Is this Correct?

**Comment by jsuarez5341** [comment]
No -- it appears you've overwritten the pretrained policy (e.g. TEST=False). When you train from scratch, by default it will save over the baseline that ships with the platform. Make sure you have a clean fork and reopen/post on Discord if issues persist
