### ISSUE TITLE
[Docs] Incorrect Repo

### ISSUE THREAD

**Issue by krvnu** [jsuarez5341/neural-mmo#42]
**Insufficient**:  User Guide - Installation docs ([link](https://jsuarez5341.github.io/neural-mmo/build/html/rst/userguide.html#icon-installation)) point to incorrect starter kit to clone "https://gitlab.aicrowd.com/jyotish/neuralmmo-starter-kit". I believe it should be "https://gitlab.aicrowd.com/neural-mmo/neural-mmo-starter-kit".

**Comment by jsuarez5341** [comment]
Fixed. Please link issues on the Discord for faster fixes in the future
